version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    groups:
      docker-images:
        patterns: ["*"]
    labels: ["dependencies", "docker"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels: ["dependencies", "github-actions"]
